### ISSUE TITLE
Moving Repository

### ISSUE THREAD

**Issue by mcrute** [mcrute/tiny-ec2-bootstrap#25]
This is a public notice that this repository will be moving around the end of May 2021. The repository will be imported with all of its history to Alpine GitLab. The new home of the repository will be:

```
https://gitlab.alpinelinux.org/alpine/cloud/tiny-ec2-bootstrap
```

Please update your git remotes to one of these:

```
git@gitlab.alpinelinux.org:alpine/cloud/tiny-ec2-bootstrap.git
https://gitlab.alpinelinux.org/alpine/cloud/tiny-ec2-bootstrap.git
```

I will comment on this issue one day before the move begins and close it before I being the migration. After that time this GitHub repository will redirect everyone to the GitLab repository.

**Comment by tomalok** [comment]
@mcrute - I'm not sure this has happened yet or not.

Either way, I've forked this repo over to https://gitlab.alpinelinux.org/tomalok/tiny-cloud-bootstrap to move forward with
* supporting more cloud providers
* moving cloud-specific and bootstrap-specific stuff out of https://github.com/mcrute/alpine-ec2-ami (which was also forked over to https://gitlab.alpinelinux.org/tomalok/alpine-cloud-images) so that `cloud-init` image flavors can be built without tripping over similar functionality we've put in there (mdev scripts, networking, EBS aliasing, etc.)

Forthcoming changes to tiny-cloud-bootstrap and alpine-cloud-images could be extensive, I feel better having a safer place to play...

**Comment by mcrute** [comment]
@tomalok sorry, I've once again had very limited time to focus on this project. I can not access your fork, can you give me at least read access?

The migration has been completed and the new official URL is https://gitlab.alpinelinux.org/alpine/cloud/tiny-ec2-bootstrap.

We need Alpine admins to make this public but you should have full maintainer access as a member of the cloud team, I anticipate it being made public on Alpine GitLab very soon. I will be purging this repo on GitHub and marking it as moved this weekend. Please migrate future changes to the official repository.
