### ISSUE TITLE
Support IMDSv2

### ISSUE THREAD

**Issue by mcrute** [mcrute/tiny-ec2-bootstrap#6]
IMDSv2 requires an additional [authorization token](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html) before metadata can be fetched. New instances are configured by default to use this new IMDS version. tiny-ec2-bootstrap should support both the old and new IMDS versions.

Originally from mcrute/alpine-ec2-ami#64

**Comment by junkb** [comment]
i've submitted a pull request [i think :) ].  imds token retrieval requires http put, which means wget can't be used.  i've used curl instead, so it's a little incongruous.  given that, if it were my project, i'd probably replace the wget commands with curl, but it's not :) .  i'd be happy to do that too though if wanted.

i'm not very familiar with alpine or openrc, so i've made some assumptions about how things work, and i've also only minimally tested this, with an already running ec2 instance, not an ami creation/ec2 instance deployment process [i still have a lot to learn about packer and the alpine-ec2-ami build process]

**Comment by tomalok** [comment]
just did a quick test -- adding `curl` to a stock `alpine:latest` container, aded ~2.2 MiB -- doing the same with standalone `wget` added only ~500 KiB.

While `busybox`'s `wget` lacks the ability to do PUT, the standalone `wget` does support PUT via `--method=PUT` and payload can be supplied with `--body-data=<string>` or `--body-file=<file>`.

**Comment by junkb** [comment]
that's a good idea.  do you want me to submit a pull request that uses nc?

**Comment by mcrute** [comment]
The Alpine package has been updated and is [pending merge](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/7561). It should hopefully be in edge within the next day or so and then officially in the next Alpine release.

**Comment by mcrute** [comment]
This was merged this morning (PST) to Alpine Edge.

**Comment by the-maldridge** [comment]
This did not make it in time for the 3.11.6 AMI set did it?

**Comment by tomalok** [comment]
Unless there's a significant security issue that needs to be addressed, new versions of packages usually don't get backported to Alpine versions that were already cut.  The 3.11 branch was cut back in Nov 2019, this got into edge early in May 2020, 3.12 branch was cut later in the month -- so it's in 3.12, but we haven't officially released a 3.12 AMI because of some ongoing automation work in progress in the alpine-ec2-ami repo.

There are some significant things that _have_ landed there, including IMDSv2, and IPv6/secondary IPv4/ENI hotplug.  I might do an AMI release by hand to (hopefully) hold us over in the interim with fresh 3.12.1 and edge AMIs.

**Comment by the-maldridge** [comment]
@tomalok Thanks for the clarification.  I didn't have the alpine merge windows handy so thanks for saving me the effort of finding them!

**Comment by tomalok** [comment]
FYI @the-maldridge we recently built and [released Alpine 3.12.1](https://github.com/mcrute/alpine-ec2-ami/blob/master/releases/README.md) AMIs a couple days ago.

**Comment by the-maldridge** [comment]
@tomalok thanks for the heads up.  I'll migrate to those in my next maintenance window!
