### ISSUE TITLE
Exit code from tee is reported

### ISSUE THREAD

**Issue by graywolf-at-work** [mcrute/tiny-ec2-bootstrap#9]
I think that this https://github.com/mcrute/tiny-ec2-bootstrap/blob/07a0b9f3c881f3efdc7ef31aa179047be835262a/tiny-ec2-bootstrap#L62

report exit code from tee and not from the user-data.sh. Am I wrong?

I can attemp to make a patch if there is a willingness to merge it.

**Comment by mcrute** [comment]
That does look correct. I'd be happy to accept a patch for this. Although I'd prefer something that only impacts the execution of the user data script and not a global patch like `set -o pipefail` because a failure of this script will cause user instances to not bootstrap and could leave a large launch job in a pretty weird state. Thanks!

**Comment by graywolf-at-work** [comment]
So I've rewrote the `_user_data`, please take a look and leave some feedback :)

**Comment by mcrute** [comment]
This change will be released as 1.3.3 and is being tracked for merge into upstream as [MR-8158](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/8158). Thanks for your contributions!
